stages:
  - build
  - push
  - deploy

variables:
  DOCKER_USERNAME: arush3339

before_script:
  - docker login -u $DOCKER_USERNAME -p "Arush@2402" docker.io

build_image:
  stage: build
  script:
    - echo "Building Makemates frontend ..."
    - echo "$DOCKER_USERNAME/makemates-frontend" | xargs -I {} docker build -t {} frontend
    - echo "Building Makemates backend ..."
    - echo "$DOCKER_USERNAME/makemates-backend" | xargs -I {} docker build -t {} backend
    - docker info | grep username
  tags:
    - makemates
  only:
    - main

push_image:
  stage: push
  script:
    - echo "pushing:$DOCKER_USERNAME/makemates-frontend"
    - docker push $DOCKER_USERNAME/makemates-frontend
    - echo "pushing:\ $DOCKER_USERNAME/makemates-backend"
    - docker push $DOCKER_USERNAME/makemates-backend
  tags:
    - makemates
  only:
    - main

deploy_image:
  stage: deploy
  script:
    - echo "getting deployments details:"
    - echo "Deploying frontend:"
    - kubectl get deploy $DOCKER_USERNAME/makemates-frontend || kubectl apply -f cluster-provision/frontend-deloy.yml --create-namespace -n makemates
    - kubectl set image deployment/$DOCKER_USERNAME/makemates-frontend frontend-container=$DOCKER_USERNAME/makemates-frontend:latest"
    - kubectl get deploy $DOCKER_USERNAME/makemates-backend || kubectl apply -f cluster-provision/backend-deloy.yml --create-namespace -n makemates
    - kubectl set image deployment/$DOCKER_USERNAME/makemates-backend backend-container=$DOCKER_USERNAME/makemates-backend:latest"
    - echo "deployment done...."
  tags:
    - makemates
  only:
    - main
