services:
  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:5000
  #   depends_on:
  #     - backend

  # backend:
  #   build: ./backend
  #   container_name: backend
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - PORT=8000
  #     - DATABASE_URL=postgresql://postgres:password@postgres:5432/mydb
  #     - MINIO_ENDPOINT=http://minio:9000
  #     - RABBITMQ_URL=amqp://rabbitmq:5672
  #   depends_on:
  #     - postgres
  #     - minio
  #     - rabbitmq
  #   volumes:
  #     - ./backend:/app
  #   restart: always

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  minio_data:
