apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-hostpath-pvc-custom
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath-custom
