apiVersion: v1
kind: Pod
metadata:
  name: test-hostpath-pod-custom
spec:
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-hostpath-pvc-custom
  containers:
    - name: test-container
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: test-volume
