/**
 * @fileoverview Root layout component that wraps the entire application.
 * Provides global styles, fonts, and context providers.
 */

// Next.js core
import type { Metadata } from "next";
import dynamic from "next/dynamic";

// Fonts
import { Inter } from "next/font/google";

// Styles
import "./globals.css";

// UI Components
import { Toaster } from "react-hot-toast";

// Dynamic imports
const AuthContextProvider = dynamic(() => import("./context/AuthContext.tsx"));

const ChatContextProvider = dynamic(() => import("./context/ChatContext.tsx"));

// Font configuration
const inter = Inter({ subsets: ["latin"], display: "swap" });

/**
 * Metadata configuration for the application
 */
export const metadata: Metadata = {
  title: "Makemates",
  description: "Generated by create next app",
};

/**
 * Root layout component that provides the basic structure for all pages
 *
 * @param {Object} props - Component props
 * @param {React.ReactNode} props.children - Child components to render
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link
        rel="icon"
        href="/makemates_client/public/favicon.ico"
        type="image/png"
        sizes="any"
      />

      <body
        className={`${inter.className} bg-slate-200 `}
        suppressHydrationWarning
      >
        <AuthContextProvider>
          <ChatContextProvider>
            <Toaster position="bottom-center" />
            {children}
          </ChatContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
